apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  namespace: flask
  labels:
    app: flask
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: flask
    app: {{ .Release.Name }}

